### ISSUE TITLE
Error starting blueproximity

### ISSUE THREAD

**Issue by Thor77** [Thor77/Blueproximity#14]
Error reported is:

X Error: BadDevice, invalid or uninitialized input device 169
Major opcode:  147
Minor opcode:  3
Resource id:  0x0
Failed to open device
X Error: BadDevice, invalid or uninitialized input device 169
Major opcode:  147
Minor opcode:  3
Resource id:  0x0
Failed to open device
Traceback (most recent call last):
File "/usr/share/blueproximity/proximity.py", line 728, in &lt;module&gt;
pGui = ProximityGUI(p,config,new_config)
File "/usr/share/blueproximity/proximity.py", line 108, in __init__
self.window.set_icon(gtk.gdk.pixbuf_new_from_file(dist_path + icon_base))
gobject.GError: Couldn't recognize the image file format for file '/usr/share/blueproximity/blueproximity_base.svg'

**Comment by Thor77** [comment]
Logged In: YES 
user_id=1312539
Originator: NO

This Tracker item was closed automatically by the system. It was
previously set to a Pending status, and the original submitter
did not respond within 14 days (the time period specified by
the administrator of this Tracker).
(By sf-robot)

**Comment by Thor77** [comment]
Logged In: YES 
user_id=114903
Originator: NO

Ok, the problem seems to be that the kubuntu kde does not really support .svg files at the system tray. I have noted that problem. To fix it yourself you should create .png files from the .svg graphics and change the icons' names in the proximity.py file.
I will fix that in the next minor release. I first have to find a way to detect a running KDE since svg would make a better format but only GNOME really supports it (as a program icon).

I hope this helps.
(By highno)

**Comment by Thor77** [comment]
Logged In: YES 
user_id=1889396
Originator: NO

Hi, I've now created a SourceForge account (effrafax).

The o/s is Kubuntu Feisty, all up to date.
(By effrafax)

**Comment by Thor77** [comment]
Logged In: NO 

Sorry, this was for the latest 1.2 release.

All dependencies installed (1.1.8 ran okay).
(By nobody)

**Comment by Thor77** [comment]
Logged In: NO 

Sorry, this was for the latest 1.2 release.

All dependencies installed (1.1.8 ran okay).
(By nobody)
